Pages/Buildings/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly BuildingService _buildingService;

        public DeleteModel(BuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        [BindProperty]
        public Building Building { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);

            if (Building == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);

            if (Building != null)
            {
                await _buildingService.DeleteBuildingAsync(id);
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Buildings/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Data.Queries;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin,Manager,Resident")]
    public class DetailsModel : PageModel
    {
        private readonly BuildingService _buildingService;
        private readonly ReservationService _reservationService;

        [BindProperty]
        public Building Building { get; set; }
        public IList<Reservation> Reservations { get; set; }

        [BindProperty] //Data has to be binded for the inputs to hold their state (this is only required if using Filter toolbar)
        public ReservationQuery Query { get; set; } = new ReservationQuery { };

        public DetailsModel(BuildingService buildingService, ReservationService reservationService)
        {
            _buildingService = buildingService;
            _reservationService = reservationService;
        }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);
            //Setting the building Id in the query since we're looking at a specific building page
            Query.BuildingId = id;
            Reservations = await _reservationService.GetReservationsAsync(Query);

            if (Building == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //Building is binded, so find the ID, then full get object
            Building = await _buildingService.GetBuildingAsync(Building.Id);

            Query.BuildingId = Building.Id;

            Reservations = await _reservationService.GetReservationsAsync(Query);
            return Page();
        }
    }
}

Pages/Buildings/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin,Manager")]
    public class EditModel : PageModel
    {
        private readonly BuildingService _buildingService;

        public EditModel(BuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        [BindProperty]
        public Building Building { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);

            if (Building == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Building = await _buildingService.GetBuildingAsync(Building.Id);

            if (Building == null)
            {
                return NotFound();
            }

            await _buildingService.UpdateBuildingAsync(Building);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Reservations/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Areas.Identity;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Reservations
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly ReservationService _reservationService;
        private readonly UserService _ApplicationUserService;

        public DeleteModel(ReservationService reservationService, UserService ApplicationUserService)
        {
            _reservationService = reservationService;
            _ApplicationUserService = ApplicationUserService;
        }

        [BindProperty]
        public Reservation Reservation { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Reservation = await _reservationService.GetReservationAsync(id);

            if (Reservation == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Reservation = await _reservationService.GetReservationAsync(id);
            bool isAuth = _reservationService.IsUserOwner(User.Identity.GetId(), Reservation);

            if (!isAuth)
            {
                return Forbid();
            }

            await _reservationService.DeleteReservationAsync(id);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Reservations/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Reservations
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ReservationService _reservationService;

        public DetailsModel(ReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        public Reservation Reservation { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Reservation = await _reservationService.GetReservationAsync(id);

            if (Reservation == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Reservations/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Areas.Identity;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Reservations
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly ReservationService _reservationService;
        private readonly BuildingService _buildingService;
        [BindProperty]
        public Reservation Reservation { get; set; }
        public Building Building { get; set; }

        public EditModel(ReservationService reservationService, BuildingService buildingService)
        {
            _reservationService = reservationService;
            _buildingService = buildingService;
        }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {

            Reservation = await _reservationService.GetReservationAsync(id);

            //TODO: Move to model
            //Reservation.Date = Reservation.StartTime;

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            /*
             * Reservation.Building is not lazyloaded! so we have to manually add it here
             * making it ready for the page ti be used (for input settings; min, max, etc)
             */
            Reservation.Building = await _buildingService.GetBuildingAsync(Reservation.BuildingId);

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Reservation == null)
            {
                return NotFound();
            }

            bool isAuth = _reservationService.IsUserOwner(User.Identity.GetId(), Reservation);

            // Checking if the current user is the owner of the reservation
            if (isAuth || User.IsInRole("Admin"))
            {
                ServiceResult result = await _reservationService.UpdateReservationAsync(Reservation);

                if (!result.Success)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error);
                    }
                }
            }
            else
            {
                return Forbid();
            }
            //return Page();
            return RedirectToPage("./Index");
        }
    }
}

Pages/Roles/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data;
using VPM.Services;

namespace VPM.Pages.Roles
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly RoleService _roleService;

        public DeleteModel(RoleService roleService)
        {
            _roleService = roleService;
        }

        [BindProperty]
        public ApplicationRole Role { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Role = await _roleService.GetRoleAsync(id);

            if (Role == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await _roleService.DeleteRoleAsync(id);

            if (!result.Success)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                    return Page();
                }

            }

            return RedirectToPage("./Index");
        }
    }
}

ViewComponents/ReservationListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Data.Queries;
using VPM.Services;

namespace VPM.ViewComponents
{
    public class AvailableInputs
    {
        public bool ByValidity { get; set; } = false;
        public bool ByUnit { get; set; } = false;
        public bool ByVehiclePlateNumber { get; set; } = false;
        public bool ByBuilding { get; set; } = false;
        public bool ByDate { get; set; } = false;
        public bool ByResident { get; set; } = false;
    }

    [ViewComponent(Name = "ReservationList")]
    public class ReservationListViewComponent : ViewComponent
    {
        private readonly BuildingService _buildingService;
        public ReservationListViewComponent(BuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        public IList<Reservation> Reservations { get; set; }
        public ReservationQuery Query { get; set; }
        public AvailableInputs AvailableInputs { get; set; }
        public SelectList BuildingOptions { get; set; } //Used to populate Building drop-down-list
        public async Task<IViewComponentResult> InvokeAsync(IList<Reservation> reservations, ReservationQuery query)
        {
            BuildingOptions = new SelectList(_buildingService.GetBuildings(), nameof(Building.Id), nameof(Building.Name));
            
            Query = query; //Query is used to set the state of the tool-bar according to the shown query
            Reservations = reservations; //To generate the list

            if (User.IsInRole("Admin"))
            {
                AvailableInputs = new AvailableInputs
                {
                    ByValidity = true,
                    ByUnit = true,
                    ByBuilding = true,
                    ByVehiclePlateNumber = true,
                    ByDate = true,
                    ByResident = true
                };
            }
            else if (User.IsInRole("Manager"))
            {
                AvailableInputs = new AvailableInputs
                {
                    ByValidity = true,
                    ByUnit = true,
                    ByBuilding = false,
                    ByVehiclePlateNumber = true,
                    ByDate = true,
                    ByResident = true
                };
            }
            else
            {
                AvailableInputs = new AvailableInputs
                {
                    ByValidity = true,
                    ByUnit = true,
                    ByBuilding = false,
                    ByVehiclePlateNumber = true,
                    ByDate = true,
                    ByResident = false
                };
            }

            return View(this);
        }
    }
}

ViewComponents/UserListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Data.Queries;
using VPM.Services;
using VPM.Data;

namespace VPM.ViewComponents
{
    public class UserFilterInput : FilterInput
    {
        public bool ByFullName { get; set; } = false;
        public bool ByEmail { get; set; } = false;
        public bool ByRole { get; set; } = false;
        public bool ByUnit { get; set; } = false;
        public bool ByBuilding { get; set; } = false;
    }

    [ViewComponent(Name = "UserList")]
    public class UserListViewComponent : ViewComponent
    {

        public IList<ApplicationUser> Users { get; set; }
        public UserQuery Query { get; set; }
        public UserFilterInput Input { get; set; }
        public SelectList RoleOptions { get; set; } //Used to populate Role drop-down-menu
        //public ApplicationRole Role { get; set; } //TODO: Shouldn't this be ApplicationRole?
        public SelectList BuildingOptions { get; set; } //Used to populate Building drop-down-list

        public UserListViewComponent(RoleService roleService, BuildingService buildingService)
        {
            //Getting list of roles, to populate the drop-down-menu
            RoleOptions = new SelectList(roleService.GetRoles(), nameof(ApplicationRole.Name), nameof(ApplicationRole.Name));
            //Getting list of buildings, to populate the drop-down-menu
            BuildingOptions = new SelectList(buildingService.GetBuildings(), nameof(Building.Id), nameof(Building.Name));
        }

        public async Task<IViewComponentResult> InvokeAsync(IList<ApplicationUser> users, UserQuery query, UserFilterInput input)
        {
            Query = query ?? throw new NotImplementedException("Query cannot be null"); //Query is used to set the state of the tool-bar according to the shown query
            Users = users ?? throw new NotImplementedException("Users cannot be null"); //To generate the list
            Input = input ?? throw new NotImplementedException("Input cannot be null"); //Input has to be give as parameter

            return View(this);
        }
    }
}

Pages/Users/Delete.cshtml
@page
@model VPM.Pages.Users.DeleteModel
@{
    ViewData["Title"] = "User | Delete";
}

<h1>Delete User</h1>
<h3>Are you sure you want to delete this user?</h3>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Building.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Building.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Building.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Building.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Unit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Unit)
        </dd>
    </dl>
    <hr />
    <form method="post">
        <input type="hidden" asp-for="ApplicationUser.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">
            <input type="button" value="Back to List" class="btn btn-dark" />
        </a>
    </form>
</div>

Pages/Users/Details.cshtml
@page
@model VPM.Pages.Users.DetailsModel
@{
    ViewData["Title"] = "User | Details";
}

<h1>User Details</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Building.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Building.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Building.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Building.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Unit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Unit)
        </dd>
    </dl>
    <a asp-page="./Edit" asp-route-id="@Model.ApplicationUser.Id"><input type="button" value="Edit" class="btn btn-warning" /></a> |
    <a asp-page="./Index">
        <input type="button" value="Back to List" class="btn btn-dark" />
    </a>
</div>

<hr />

<h2>Reservations</h2>
<hr />
@await Component.InvokeAsync("ReservationList", new { Reservations = Model.Reservations, Query = Model.Query })

Pages/Users/Edit.cshtml
@page
@model VPM.Pages.Users.EditModel
@{
    ViewData["Title"] = "User | Edit";
}

<h1>Edit User</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Building.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Building.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Building.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Building.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser.Unit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Unit)
        </dd>
    </dl>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ApplicationUser.Id" />
            <div class="form-group">
                <label asp-for="Input.Unit"></label>
                <input asp-for="Input.Unit" class="form-control" value="@Model.ApplicationUser.Unit"/>
                <span asp-validation-for="Input.Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Building</label>
                <select asp-for="Input.SelectedBuildingId" asp-items="Model.BuildingOptions" class="form-control"></select>
            </div>
            <div class="form-group">
                <label>Role</label>
                <select asp-for="Input.SelectedRoleName" asp-items="Model.RoleOptions" class="form-control"></select>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" /> |
                <a asp-page="./Index">
                    <input type="button" value="Back to List" class="btn btn-dark" />
                </a>
            </div>
        </form>
    </div>
</div>

Pages/Users/Index.cshtml
@page
@model VPM.Pages.Users.IndexModel
@{
    ViewData["Title"] = "Users";
}

<script type="text/javascript">
    // Function to generate a random password
    function setRandomPassword() {
        var randomstring = Math.random().toString(36).slice(-8);
        document.getElementById("Input_UserPassword").value = randomstring;
    }
</script>

<h2>Add new user</h2>
<hr />

<div asp-validation-summary="All" class="text-danger"></div>

<form method="post">
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Input.UserEmail" class="control-label"></label>
                <input asp-for="Input.UserEmail" class="form-control" />
                <span asp-validation-for="Input.UserEmail" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Input.UserFullName" class="control-label"></label>
                <input asp-for="Input.UserFullName" class="form-control" />
                <span asp-validation-for="Input.UserFullName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="Input.UserPassword" class="control-label"></label>
                <input asp-for="Input.UserPassword" class="form-control" />
                <span asp-validation-for="Input.UserPassword" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Role</label>
                <select asp-for="Input.SelectedRoleName" asp-items="Model.RoleOptions" class="form-control"></select>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <label asp-for="Input.Unit"></label>
                <input asp-for="Input.Unit" class="form-control" />
                <span asp-validation-for="Input.Unit" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Building</label>
                <select asp-for="Input.SelectedBuildingId" asp-items="Model.BuildingOptions" class="form-control"></select>
            </div>
        </div>
        <div class="col-md-4">
            <label>Tools</label>
            <div class="form-group">
                <input type="button" value="Generate Password" class="btn btn-secondary" onclick="setRandomPassword()" />
                <hr />
                <input type="submit" value="Add User" class="btn btn-primary" /> |
                <a asp-page="../Admin/Users">
                    <input type="button" value="Cancel" class="btn btn-dark" />
                </a>
            </div>
        </div>
    </div>
</form>

@await Component.InvokeAsync("UserList", new { Users = Model.Users, Query = Model.Query, Input = Model.FilterInput })

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}