Pages/Buildings/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Vereyon.Web;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly BuildingService _buildingService;
        private readonly IFlashMessage _flashMessage;
        public CreateModel(BuildingService buildingService, IFlashMessage flashMessage)
        {
            _buildingService = buildingService;
            _flashMessage = flashMessage;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Building Building { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Validate Inputs; AllowedReservationPerUnit Vs VisitorParkingCount
            // AllowedReservationPerUnit cannot be more than VisitorParkingCount
            if (Building.AllowedReservationPerUnit > Building.VisitorParkingCount)
            {
                _flashMessage.Danger("Invalid Input; Allowed Reservations Per Unit cannot be more than the Total Number of Available Parkings");
                return Page();
            }

            await _buildingService.CreateBuildingAsync(Building);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Buildings/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly BuildingService _buildingService;

        public DeleteModel(BuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        [BindProperty]
        public Building Building { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);

            if (Building == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);

            if (Building != null)
            {
                await _buildingService.DeleteBuildingAsync(id);
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Buildings/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Data.Queries;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin,Manager,Resident")]
    public class DetailsModel : PageModel
    {
        private readonly BuildingService _buildingService;
        private readonly ReservationService _reservationService;

        [BindProperty]
        public Building Building { get; set; }
        public IList<Reservation> Reservations { get; set; }

        [BindProperty] //Data has to be binded for the inputs to hold their state (this is only required if using Filter toolbar)
        public ReservationQuery Query { get; set; } = new ReservationQuery { };

        public DetailsModel(BuildingService buildingService, ReservationService reservationService)
        {
            _buildingService = buildingService;
            _reservationService = reservationService;
        }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);
            //Setting the building Id in the query since we're looking at a specific building page
            Query.BuildingId = id;
            Reservations = await _reservationService.GetReservationsAsync(Query);

            if (Building == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //Building is binded, so find the ID, then full get object
            Building = await _buildingService.GetBuildingAsync(Building.Id);

            Query.BuildingId = Building.Id;

            Reservations = await _reservationService.GetReservationsAsync(Query);
            return Page();
        }
    }
}

Pages/Buildings/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Buildings
{
    [Authorize(Roles = "Admin,Manager")]
    public class EditModel : PageModel
    {
        private readonly BuildingService _buildingService;

        public EditModel(BuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        [BindProperty]
        public Building Building { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Building = await _buildingService.GetBuildingAsync(id);

            if (Building == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Building = await _buildingService.GetBuildingAsync(Building.Id);

            if (Building == null)
            {
                return NotFound();
            }

            await _buildingService.UpdateBuildingAsync(Building);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Reservations/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Services;

namespace VPM.Pages.Reservations
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ReservationService _reservationService;

        public DetailsModel(ReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        public Reservation Reservation { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Reservation = await _reservationService.GetReservationAsync(id);

            if (Reservation == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ViewComponents/BuildingListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Data.Queries;

namespace VPM.ViewComponents
{
    [ViewComponent(Name = "BuildingList")]
    public class BuildingListViewComponent : ViewComponent
    {
        public IList<Building> Buildings { get; set; }
        public BuildingQuery Query { get; set; }

        public async Task<IViewComponentResult> InvokeAsync(IList<Building> buildings, BuildingQuery query)
        {
            Query = query; //Query is used to set the state of the tool-bar according to the shown query
            Buildings = buildings; //To generate the list

            return View(this);
        }
    }
}

ViewComponents/ReservationListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VPM.Data.Entities;
using VPM.Data.Queries;
using VPM.Services;

namespace VPM.ViewComponents
{
    public class AvailableInputs
    {
        public bool ByValidity { get; set; } = false;
        public bool ByUnit { get; set; } = false;
        public bool ByVehiclePlateNumber { get; set; } = false;
        public bool ByBuilding { get; set; } = false;
        public bool ByDate { get; set; } = false;
        public bool ByResident { get; set; } = false;
    }

    [ViewComponent(Name = "ReservationList")]
    public class ReservationListViewComponent : ViewComponent
    {
        private readonly BuildingService _buildingService;
        public ReservationListViewComponent(BuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        public IList<Reservation> Reservations { get; set; }
        public ReservationQuery Query { get; set; }
        public AvailableInputs AvailableInputs { get; set; }
        public SelectList BuildingOptions { get; set; } //Used to populate Building drop-down-list
        public async Task<IViewComponentResult> InvokeAsync(IList<Reservation> reservations, ReservationQuery query)
        {
            BuildingOptions = new SelectList(_buildingService.GetBuildings(), nameof(Building.Id), nameof(Building.Name));
            
            Query = query; //Query is used to set the state of the tool-bar according to the shown query
            Reservations = reservations; //To generate the list

            if (User.IsInRole("Admin"))
            {
                AvailableInputs = new AvailableInputs
                {
                    ByValidity = true,
                    ByUnit = true,
                    ByBuilding = true,
                    ByVehiclePlateNumber = true,
                    ByDate = true,
                    ByResident = true
                };
            }
            else if (User.IsInRole("Manager"))
            {
                AvailableInputs = new AvailableInputs
                {
                    ByValidity = true,
                    ByUnit = true,
                    ByBuilding = false,
                    ByVehiclePlateNumber = true,
                    ByDate = true,
                    ByResident = true
                };
            }
            else
            {
                AvailableInputs = new AvailableInputs
                {
                    ByValidity = true,
                    ByUnit = true,
                    ByBuilding = false,
                    ByVehiclePlateNumber = true,
                    ByDate = true,
                    ByResident = false
                };
            }

            return View(this);
        }
    }
}

ViewComponents/WeeklyCalendarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VPM.Data;
using VPM.Data.Entities;

namespace VPM.ViewComponents
{
    [ViewComponent(Name = "WeeklyCalendar")]
    public class WeeklyCalendarViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        public IList<Reservation> ThisWeekReservations { get; set; }
        public IList<DateTime> ThisWeekDays { get; set; }

        public string[] Hours;

        public WeeklyCalendarViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public string[] HoursQuarter =
        {
            "12:00 AM",
            "12:15 AM",
            "12:30 AM",
            "12:45 AM",
            "1:00 AM",
            "1:15 AM",
            "1:30 AM",
            "1:45 AM",
            "2:00 AM",
            "2:15 AM",
            "2:30 AM",
            "2:45 AM",
            "3:00 AM",
            "3:15 AM",
            "3:30 AM",
            "3:45 AM",
            "4:00 AM",
            "4:15 AM",
            "4:30 AM",
            "4:45 AM",
            "5:00 AM",
            "5:15 AM",
            "5:30 AM",
            "5:45 AM",
            "6:00 AM",
            "6:15 AM",
            "6:30 AM",
            "6:45 AM",
            "7:00 AM",
            "7:15 AM",
            "7:30 AM",
            "7:45 AM",
            "8:00 AM",
            "8:15 AM",
            "8:30 AM",
            "8:45 AM",
            "9:00 AM",
            "9:15 AM",
            "9:30 AM",
            "9:45 AM",
            "10:00 AM",
            "10:15 AM",
            "10:30 AM",
            "10:45 AM",
            "11:00 AM",
            "11:15 AM",
            "11:30 AM",
            "11:45 AM",
            "12:00 PM",
            "12:15 PM",
            "12:30 PM",
            "12:45 PM",
            "1:00 PM",
            "1:15 PM",
            "1:30 PM",
            "1:45 PM",
            "2:00 PM",
            "2:15 PM",
            "2:30 PM",
            "2:45 PM",
            "3:00 PM",
            "3:15 PM",
            "3:30 PM",
            "3:45 PM",
            "4:00 PM",
            "4:15 PM",
            "4:30 PM",
            "4:45 PM",
            "5:00 PM",
            "5:15 PM",
            "5:30 PM",
            "5:45 PM",
            "6:00 PM",
            "6:15 PM",
            "6:30 PM",
            "6:45 PM",
            "7:00 PM",
            "7:15 PM",
            "7:30 PM",
            "7:45 PM",
            "8:00 PM",
            "8:15 PM",
            "8:30 PM",
            "8:45 PM",
            "9:00 PM",
            "9:15 PM",
            "9:30 PM",
            "9:45 PM",
            "10:00 PM",
            "10:15 PM",
            "10:30 PM",
            "10:45 PM",
            "11:00 PM",
            "11:15 PM",
            "11:30 PM",
            "11:45 PM",
        };

        public string[] HoursHalf =
        {
            "12:00 AM",
            "12:30 AM",
            "1:00 AM",
            "1:30 AM",
            "2:00 AM",
            "2:30 AM",
            "3:00 AM",
            "3:30 AM",
            "4:00 AM",
            "4:30 AM",
            "5:00 AM",
            "5:30 AM",
            "6:00 AM",
            "6:30 AM",
            "7:00 AM",
            "7:30 AM",
            "8:00 AM",
            "8:30 AM",
            "9:00 AM",
            "9:30 AM",
            "10:00 AM",
            "10:30 AM",
            "11:00 AM",
            "11:30 AM",
            "12:00 PM",
            "12:30 PM",
            "1:00 PM",
            "1:30 PM",
            "2:00 PM",
            "2:30 PM",
            "3:00 PM",
            "3:30 PM",
            "4:00 PM",
            "4:30 PM",
            "5:00 PM",
            "5:30 PM",
            "6:00 PM",
            "6:30 PM",
            "7:00 PM",
            "7:30 PM",
            "8:00 PM",
            "8:30 PM",
            "9:00 PM",
            "9:30 PM",
            "10:00 PM",
            "10:30 PM",
            "11:00 PM",
            "11:30 PM",
        };

        public string[] HoursFull =
        {
            "12:00 AM",
            "1:00 AM",
            "2:00 AM",
            "3:00 AM",
            "4:00 AM",
            "5:00 AM",
            "6:00 AM",
            "7:00 AM",
            "8:00 AM",
            "9:00 AM",
            "10:00 AM",
            "11:00 AM",
            "12:00 PM",
            "1:00 PM",
            "2:00 PM",
            "3:00 PM",
            "4:00 PM",
            "5:00 PM",
            "6:00 PM",
            "7:00 PM",
            "8:00 PM",
            "9:00 PM",
            "10:00 PM",
            "11:00 PM",
        };

        public string[] GetHours(AllowedReservationIntervals reservationIntervals)
        {
            return reservationIntervals switch
            {
                AllowedReservationIntervals.QH => HoursQuarter,
                AllowedReservationIntervals.HH => HoursHalf,
                AllowedReservationIntervals.FH => HoursFull,
                _ => throw new NotImplementedException(),
            };
        }

        public IList<DateTime> GetWeekDays()
        {
            //Get a list of reservations for the next 6 days (including today)
            DateTime today = DateTime.Today;

            List<DateTime> ThisWeekDays = new List<DateTime>
            {
                today
            };
            for (int i = 1; i < 7; i++)
            {
                ThisWeekDays.Add(today.AddDays(i));
            }

            return ThisWeekDays;
        }

        public IList<Reservation> GetWeekReservations()
        {
            //TODO: Use Service to get this
            return _context.Reservations.
                    Where(r => r.StartTime >= DateTime.Today && r.EndTime <= DateTime.Today.AddDays(6)).ToList();
        }

        public async Task<IViewComponentResult> InvokeAsync(Building building)
        {

            ThisWeekDays = GetWeekDays();
            ThisWeekReservations = GetWeekReservations();
            Hours = GetHours(building.ReservationInterval);

            return View(this);
        }
    }
}

Pages/Buildings/Create.cshtml
@page
@model VPM.Pages.Buildings.CreateModel
@using VPM.Data.Entities

@{
    ViewData["Title"] = "Building | Create";
}

<script type="text/javascript">
    // Function to set the Max value for allowed reservation per unit Input.
    function setAllowedParkingPerUnitMaxValue() {
        var parkingCount = document.getElementById("Building_VisitorParkingCount").value;

        var input = document.getElementById("Building_AllowedReservationPerUnit");
        input.setAttribute("max",parkingCount);
    }
</script>

<h1>Adda a new building</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Building.Name" class="control-label"></label>
                <input asp-for="Building.Name" class="form-control" />
                <span asp-validation-for="Building.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.Address" class="control-label"></label>
                <input asp-for="Building.Address" class="form-control" />
                <span asp-validation-for="Building.Address" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Building.IsActive" checked="checked"/> @Html.DisplayNameFor(model => model.Building.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Building.VisitorParkingCount" class="control-label"></label>
                <input asp-for="Building.VisitorParkingCount" class="form-control" min="1" onchange="setAllowedParkingPerUnitMaxValue()" />
                <span asp-validation-for="Building.VisitorParkingCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.AllowedReservationPerUnit" class="control-label"></label>
                <input asp-for="Building.AllowedReservationPerUnit" class="form-control" step="1" min="1"/>
                <span asp-validation-for="Building.AllowedReservationPerUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.AllowedReservationLength" class="control-label"></label>
                <input asp-for="Building.AllowedReservationLength" class="form-control" step="1" min="1" max="24" />
                <span asp-validation-for="Building.AllowedReservationLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.ReservationInterval" class="control-label"></label>
                <select asp-for="Building.ReservationInterval" asp-items="Html.GetEnumSelectList<AllowedReservationIntervals>()" class="form-control"></select>
                <span asp-validation-for="Building.ReservationInterval" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" /> | 
                <a asp-page="./Index">
                <input type="button" value="Back to List" class="btn btn-dark" />
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Buildings/Delete.cshtml
@page
@model VPM.Pages.Buildings.DeleteModel

@{
    ViewData["Title"] = "Building | Delete";
}

<h1>Delete building</h1>

<h3>Are you sure you want to delete this building?</h3>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.IsActive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.VisitorParkingCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.VisitorParkingCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.AllowedReservationPerUnit)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.AllowedReservationPerUnit)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.AllowedReservationLength)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.AllowedReservationLength)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Building.ReservationInterval)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Building.ReservationInterval)
        </dd>
    </dl>
    <hr />
    <form method="post">
        <input type="hidden" asp-for="Building.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">
            <input type="button" value="Back to List" class="btn btn-dark" />
        </a>
    </form>
</div>

Pages/Buildings/Details.cshtml
@page
@model VPM.Pages.Buildings.DetailsModel
@{
    ViewData["Title"] = "Building | Details";
}

<h1>Building Details</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <dl class="row">
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.Name)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.Name)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.Address)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.Address)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.IsActive)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.IsActive)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.VisitorParkingCount)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.VisitorParkingCount)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.AllowedReservationPerUnit)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.AllowedReservationPerUnit)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.AllowedReservationLength)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.AllowedReservationLength)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.ReservationInterval)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.ReservationInterval)
            </dd>
            <dt class="col-sm-6">
                @Html.DisplayNameFor(model => model.Building.Created)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.Building.Created)
            </dd>
            <dd class="col-sm-12">
                <hr />
                @{
                    if (User.IsInRole("Admin"))
                    {
                        <a asp-page="./Edit" asp-route-id="@Model.Building.Id">
                            <input type="button" value="Edit" class="btn btn-warning" /> |
                        </a>

                        <a asp-page="./Index">
                            <input type="button" value="Back to List" class="btn btn-dark" />
                        </a>
                    }
                    else if (User.IsInRole("Manager"))
                    {
                        <a asp-page="./Edit" asp-route-id="@Model.Building.Id">
                            |
                            <input type="button" value="Edit" class="btn btn-warning" />
                        </a>
                    }
                    else
                    {
                        <a asp-page="../Index">
                            <input type="button" value="Back to Home" class="btn btn-dark" />
                        </a>
                    }
                }
            </dd>
        </dl>
    </div>
    <div class="col-md-8">
        @await Component.InvokeAsync("WeeklyCalendar", new { Building = Model.Building })
    </div>
</div>
<hr />
@await Component.InvokeAsync("ReservationList", new { Reservations = Model.Reservations, Query = Model.Query })

Pages/Buildings/Edit.cshtml
@page
@model VPM.Pages.Buildings.EditModel
@using VPM.Data.Entities
@using VPM.Areas.Identity

@{
    ViewData["Title"] = "Building | Edit";
}

<h1>Edit Building</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Building.Id" />
            <div class="form-group">
                <label asp-for="Building.Name" class="control-label"></label>
                <input asp-for="Building.Name" class="form-control" />
                <span asp-validation-for="Building.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.Address" class="control-label"></label>
                <input asp-for="Building.Address" class="form-control" />
                <span asp-validation-for="Building.Address" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Building.IsActive" /> @Html.DisplayNameFor(model => model.Building.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Building.VisitorParkingCount" class="control-label"></label>
                <input asp-for="Building.VisitorParkingCount" class="form-control" />
                <span asp-validation-for="Building.VisitorParkingCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.AllowedReservationPerUnit" class="control-label"></label>
                <input asp-for="Building.AllowedReservationPerUnit" class="form-control" />
                <span asp-validation-for="Building.AllowedReservationPerUnit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.AllowedReservationLength" class="control-label"></label>
                <input asp-for="Building.AllowedReservationLength" class="form-control" />
                <span asp-validation-for="Building.AllowedReservationLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Building.ReservationInterval" class="control-label"></label>
                <select asp-for="Building.ReservationInterval" asp-items="Html.GetEnumSelectList<AllowedReservationIntervals>()" class="form-control"></select>
                <span asp-validation-for="Building.ReservationInterval" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> | 
                @{
                    if (User.IsInRole("Admin"))
                    {
                        <a asp-page="./Index">
                            <input type="button" value="Back to List" class="btn btn-dark" />
                        </a>
                    }
                    else if (User.IsInRole("Manager"))
                    {
                        <a asp-page="./Details" asp-route-id="@User.Identity.GetBuildingId()">
                            <input type="button" value="Cancel" class="btn btn-dark" />
                        </a>
                    }
                }
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Buildings/Index.cshtml
@page
@model VPM.Pages.Buildings.IndexModel
@{
    string title = "Buildings";

    ViewData["Title"] = title;
}

<div class="row">
    <div class="col-6">
        <h1>@title</h1>
    </div>
    <div class="col-6 text-right">
        <p>
            <a asp-page="Create"><input type="button" value="Add New Building" class="btn btn-primary" /></a>
        </p>
    </div>
</div>
@await Component.InvokeAsync("BuildingList", new { Buildings = Model.Buildings, Query = Model.Query })